blank_issues_enabled: false
contact_links:
  - name: Brthrs Support
    url: https://www.notion.so/brthrs/Alles-op-een-rijtje-2feb28dde84e455b93f7d748b98f6841
    about: Want to contact us instead of creating an issue?